# Tensorflow Basics

TensorFlow is an end-to-end platform for machine learning. It supports the following:

* Multidimensional-array based numeric computation (similar to <a href="https://numpy.org/" class="external">NumPy</a>.)
* GPU and distributed processing
* Automatic differentiation
* Model construction, training, and export
* And more

## Tensors (Constant)


# Tensor -----> Container

The most important attributes of a `tf.Tensor` are its `shape` and `dtype`:

* `Tensor.shape`: tells you the size of the tensor along each of its axes.
* `Tensor.dtype`: tells you the type of all the elements in the tensor.

### These ranks refer to the dimensions of tensors in TensorFlow:



1. **Rank-0 Tensor (Scalar)**: Represents a single value, like a number on a number line.
  
2. **Rank-1 Tensor (Vector)**: Represents a list of values, like a sequence of numbers.
  
3. **Rank-2 Tensor (Matrix)**: Represents a grid of values, like a table with rows and columns.
  
4. **Rank-3 Tensor**: Represents a cube of values, like stacking multiple matrices together.

5. **Higher Rank Tensors**: Represent even more complex structures, such as volumes of 3D data or collections of images.

In [1]:
import tensorflow as tf

In [2]:
#Rank-0( Scaler)----> Contains a single value
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
#Rank-1(vector)----> Contains list of values
rank_1_tensor = tf.constant([2.0, 2, 3.0])
rank_1_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 2., 3.], dtype=float32)>

In [4]:
#Rank-2(Matrix)--->rows and columns
rank_2_tensor = tf.constant([[1, 2] ,[3, 2], [4, 5]])
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 2],
       [4, 5]], dtype=int32)>

In [5]:
#Rank-3----> Collection of matrices
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 1, 23, 1, 3],
     [15, 12, 1, 3, 4]],
    [[20, 21, 23, 14, 1],
     [23, 34, 12, 1, 2]],])
rank_3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10,  1, 23,  1,  3],
        [15, 12,  1,  3,  4]],

       [[20, 21, 23, 14,  1],
        [23, 34, 12,  1,  2]]], dtype=int32)>

### Converting TensorFlow Tensors to NumPy Arrays

In [6]:
import numpy as np

In [7]:
np.array(rank_3_tensor)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10,  1, 23,  1,  3],
        [15, 12,  1,  3,  4]],

       [[20, 21, 23, 14,  1],
        [23, 34, 12,  1,  2]]], dtype=int32)

# TensorFlow implements standard mathematical operations on tensors, as well as many operations specialized for machine learning.

## Standard Mathematical Operations:
### TensorFlow provides support for basic arithmetic operations such as addition, subtraction, multiplication, and division, which can be performed element-wise on tensors.

In [8]:
tensor_1 = tf.constant([[1, 2, 3],
                       [4, 5, 6]])
tensor_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [9]:
tensor_2 = tf.constant([[11, 12, 13],
                       [14, 15, 16]])
tensor_2


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [10]:
tensor_3 = tf.constant([[21, 22, 23],
                       [24, 25, 26]])
tensor_3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[21, 22, 23],
       [24, 25, 26]], dtype=int32)>

In [11]:
#Addition in Tensorflow
tensor_1 + tensor_3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[22, 24, 26],
       [28, 30, 32]], dtype=int32)>

In [12]:
tensor_1 * tensor_3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 21,  44,  69],
       [ 96, 125, 156]], dtype=int32)>

In [13]:
5 * tensor_3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[105, 110, 115],
       [120, 125, 130]], dtype=int32)>

In [14]:
tf.transpose(tensor_3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[21, 24],
       [22, 25],
       [23, 26]], dtype=int32)>

In [15]:
#Matrix Multiplication
tf.matmul(tensor_1, tf.transpose(tensor_1))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [16]:
tf.concat([tensor_1, tensor_3], axis=0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [21, 22, 23],
       [24, 25, 26]], dtype=int32)>

# Specialized Operations for Machine Learning:
### TensorFlow offers operations specifically designed for machine learning tasks such as neural networks, optimization, loss functions, and more.


In [19]:
import tensorflow as tf

# Assuming tensor_1 is your input tensor
# Make sure tensor_1 is properly defined with the correct shape and values

# Cast tensor_1 to float32 if it's not already in float format
tensor_1 = tf.cast(tensor_1, tf.float32)

# Check for NaN or infinite values
if tf.reduce_any(tf.math.is_nan(tensor_1)) or tf.reduce_any(tf.math.is_inf(tensor_1)):
    print("Input tensor contains NaN or infinite values.")
else:
    # Apply softmax along the appropriate axis (typically the last axis)
    softmax_output = tf.nn.softmax(tensor_1, axis=-1)


In [20]:
tensor_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [21]:
tf.reduce_sum(tensor_1)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

# Variables

In [22]:
import tensorflow as tf

In [23]:
var_1 = tf.Variable([0, 1.12, 0])
var_1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0.  , 1.12, 0.  ], dtype=float32)>

## Variable Assign

In [24]:
var_1.assign([1, 2, 3])
var_1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [25]:
var_1.assign_add([1, 5, 1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([2., 7., 4.], dtype=float32)>

In [26]:
var_1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2., 7., 4.], dtype=float32)>

In [27]:
#Variable can be all kinds of types, just like tensors
bool_variable = tf.Variable((False, True, False, True))
bool_variable

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([False,  True, False,  True])>

In [28]:
complex_variables = tf.Variable([5 + 4j, 6 + 1j])
complex_variables

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>

In [29]:
tf.convert_to_tensor(var_1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 7., 4.], dtype=float32)>

In [30]:
My_var = tf.constant([[21, 22],
                       [24, 25]])

In [31]:
tf.convert_to_tensor(My_var)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 22],
       [24, 25]], dtype=int32)>

In [32]:
tf.reshape(My_var, [1,4])

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[21, 22, 24, 25]], dtype=int32)>