##Numpy
 It provides efficient data structures and functions for working with arrays and matrices, making it essential for scientific computing tasks.

In [ ]:
import numpy as np

In [ ]:
ages=np.array([22, 35, 40, 45, 50])
ages

array([22, 35, 40, 45, 50])

##Array Attributes:
After creating an array, you can access its attributes such as dimensions, shape, and data type


In [ ]:
#dimensions
print(ages.ndim)

1


In [ ]:
print(ages.shape)

(5,)


In [ ]:
print(ages.dtype)

int64


##Creating Arrays with arange
To create arrays with a range of values

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(13, 50, 2)

array([13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45,
       47, 49])

In [ ]:
np.arange(1, 100, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

##Creating Arrays with linspace

In [ ]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

##Creating Arrays with Specific Values

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##Accessing, Modifying Elements & Slicing

In [ ]:
arr=np.arr([1, 2, 3, 4, 5])

In [ ]:
# Acessing Element
print(arr[0])

1


In [ ]:
#Modifing Elements
arr[1:4]=1
arr

array([1, 1, 1, 1, 5])

In [ ]:
#Positive Slicing
arr[0:3]

array([1, 1, 1])

In [ ]:
#Negative Slicing
arr[-3]

1

##Creating Multi-dimensional Arrays:

In [ ]:
a = np.array([[1,2,3,4],[4,5,4,5]])
a

array([[1, 2, 3, 4],
       [4, 5, 4, 5]])

In [ ]:
print(a.ndim)

2


In [ ]:
_3d=np.array([[[1,2,3,4],[4,5,6,7],[61,17,8,9]]])
_3d

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [61, 17,  8,  9]]])

In [ ]:
print(_3d.ndim)

3


##Accessing Elements of Multi-dimensional Arrays:

In [ ]:
#Accessing Elements
print(_3d[0, 1, 2])

6


In [ ]:
print(_3d[0,2,2])

8


In [ ]:
print(_3d[0,0,1])

2


In [ ]:
_3d[:, -2]

array([[4, 5, 6, 7]])

In [ ]:
_3d[:, :, -1]

array([[4, 7, 9]])

In [ ]:
print(_3d[:, :, 2])

[[3 6 8]]


##Mathematical functions

In [ ]:
arr=np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
sin_arr = np.sin(arr)
sin_arr

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [ ]:
cos_arr = np.cos(arr)
cos_arr

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [ ]:
tan_arr = np.tan(arr)
tan_arr

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [ ]:
log_arr = np.log(arr)
log_arr

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
exp_arr = np.exp(arr)
exp_arr

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [12]:
arr=np.array([1, 2, 3, 4, 5])
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

##Broadcasting


In [ ]:
arr1=np.array([[1, 2, 3], [4, 5, 6]])
arr2=np.array([10, 20, 30])

In [ ]:
result=arr1+arr2

In [ ]:
print(result)

[[11 22 33]
 [14 25 36]]


##Linear algebra operations

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
C = np.dot(A, B)

In [ ]:
C

array([[19, 22],
       [43, 50]])

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
A_inv = np.linalg.inv(A)
print("Original Matrix:")
print(A)
print("\nInverse Matrix:")
print(A_inv)

Original Matrix:
[[1 2]
 [3 4]]

Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


##Random number generation:

In [7]:
# Generate a 1D array with 5 random numbers between 0 and 1
random_numbers = np.random.rand(3)

print("Random numbers from uniform distribution:")
print(random_numbers)


Random numbers from uniform distribution:
[0.81388127 0.50227831 0.16609745]


In [8]:
# Generate a 1D array with 5 random numbers from standard normal distribution
random_numbers = np.random.randn(2)

print("Random numbers from standard normal distribution:")
print(random_numbers)


Random numbers from standard normal distribution:
[-0.2262892 -0.9823794]


In [3]:
# Simulate 10 trials of a binomial experiment with 5 trials and success probability of 0.5
n_trials = 10
n = 5
p = 0.5
binomial_outcomes = np.random.binomial(n, p, size=n_trials,)

print("Binomial outcomes for 10 trials:")
print(binomial_outcomes)

Binomial outcomes for 10 trials:
[3 1 4 3 4 4 3 4 3 4]
